
---
html_document: default

---

# Settlement Data and Geospatial Covariates

## Settlement Data

Settlement data plays a pivotal role in gridded population modelling as it provides critical information about the distribution and characteristics of human settlements which is key in population modelling [@Leasure; @Nieves; @Tiecke]. Various types of settlement data are available to produce gridded population estimates, each offering unique insights into the spatial and demographic patterns of human populations. Some examples of settlement data are building footprint data 
[@Chamberlain], landuse/land cover dataset [@Pandey], built-up area, residential and non-residential [@Lloyd].Recently, the advancement in highly detailed satellite imagery with high spatial resolution, along with enhancements in computer capabilities and algorithms, has facilitated the availability of building footprint automatically extracted from satellite imagery [@Gavankar; @Li; @Liu]. A building footprint is a polygon or set of polygons that defines the geometry such as the shape, size, height, or perimeter of a particular building. The global extent of these building footprint makes them an important source of settlement information for gridded population estimation.

Although remote sensing and satellite imagery provide most of the available building footprint in various formats and resolutions, National Statistical Offices (NSOs) of various countries sometimes also provide detailed settlement information collected through national surveys and questionnaires defining building locations and other attributes such as use and purpose of the building. In addition, volunteered geographic information (VGI), such as OpenStreetMap [OpenStreetMap](www.openstreetmap.org), provide an easy alternative building data source derived through manual digitising from imagery or by incorporating open building datasets. Together, these different types of settlement data help researchers at WorldPop to understand the dynamics of human populations, their spatial distribution, and how best to incorporate such settlement data into gridded population estimation.

Settlement data may come in a variety of spatial formats and resolutions depending on the data source. Common spatial data format for settlement data is a polygon shapefile which defines the perimeter or footprint extent of the buildings. Building footprint derived from satellite imagery can be converted to a high-resolution raster format and different building metrics such as count of buildings, building area, building perimeter and building height can be calculated from the available building footprint [@Jochem_Tatem].

## Key Settlement Data Sources

**Building Footprints** – WorldPop have used building footprint from a variety of sources for population modelling. These building footprints includes the following: 

**1.Maxar & Ecopia Building Footprint:** This has been the most frequently used settlement data source by WorldPop for gridded population estimations. The building footprint data is the result of a partnership between Maxar Technologies, a satellite imagery company and Ecopia AI, a geospatial data analytics company that specialises in the extraction of building footprints from remote sensing data. Through an initiative called Digitising Sub-Saharan Africa, Ecopia has extracted every building and road in 51 African countries and has made such data available for use in humanitarian response efforts across the continent with support from the Bill & Melinda Gates Foundation. More information on Digitising Sub-Saharan Africa initiative can be found here [Digitising Sub-Saharan Africa](https://www.ecopiatech.com/resources/case-study/mapping-sub-saharan-africa-to-enable-life-saving-humanitarian-aid). This dataset has also been made available to WorldPop and have been widely used in population modelling for many Sub-Saharan countries (see the Bespoke Population Modelling Section). The building footprints are polygon shapefiles that defines the geometry of a given building. The first version of the Maxar-Ecopia building footprint for Sub-Saharan Africa, version 1, was released in 2020. Recently version 2 of the footprint has also been released. Maxar and Ecopia building footprint are however closed source data and users require a license to access this dataset.

**2.Google Open Buildings:** The Google building footprint dataset is produced by Google and available at [Google Open Buildings](https://sites.research.google/open-buildings/). This building footprint is open-access and encompass 1.8 billion building detections, spanning regions in Africa, South Asia, South-East Asia, Latin America, and the Caribbean [@Google]. The first version of this building footprint, version 1 was released in 2021 and its covered exclusively African countries. Version 2 of the building footprint was also released the same year and coverage was expanded to include South and South-East Asian countries. In 2023, google released version 3 of the dataset further broadening the building footprint coverage to encompass Latin America and the Caribbean regions [@Google]. This building footprint data is a polygon shapefile and can be processed into a raster format of different spatial resolutions. The combination of open access availability and comprehensive geographical coverage makes this building footprint dataset source invaluable for in-depth analysis of settlement morphologies across countries. It also facilitates population modelling efforts, ultimately supporting evidence-based decision-making.

**3.Global Microsoft building footprint:** The global Microsoft's building footprint dataset is produced by Microsoft and was released in 2022. The data can be accessed at [GlobalMLBuildingFootprints](https://github.com/microsoft/GlobalMLBuildingFootprints) and comes in GeoJSON format,  which can be converted to other spatial formats such as a vector or raster file. This building footprint covers more than 1.2 billion buildings worldwide, covering various regions such as Africa, Caribbean nations, Europe, the Middle East, and South Asian countries [@Microsoft]. However, this building footprint has limited spatial coverage in Latin American countries, as can be seen in these [coverage maps](https://github.com/microsoft/GlobalMLBuildingFootprints#regions-included)

**4.World Settlement Footprint Layers:** The World Settlement Footprint (WSF) is a joint project of the European Space Agency (ESA) and the German Aerospace Center (DLR), in collaboration with the Google Earth Engine team[@European]. The WSF consist of different settlement products including the World Settlement Footprints (Versions 2 and 3), World Settlement Footprint Evolution, World Settlement Footprint 3D, and the Global Urban Footprint (Versions 1 and 2). The World Settlement Footprints, both Versions 2 and 3, consist of binary grid raster data with a 10-metre resolution, indicating the presence or absence of human settlements. Version 2 was initially generated in 2015, followed by an updated version in 2019 (version 2). The World Settlement Footprint 3D (WSF 3D) offers a detailed quantification of average height, total volume, total area, and the fraction of buildings at a 90-metre resolution globally.  This dataset was produced in 2021. For temporal analysis, the World Settlement Footprint Evolution (WSF-Evolution) dataset offers a 30-metre resolution, outlining global settlement changes on a yearly basis from 1985 to 2015. The Global Urban Footprint Layer, available in both Versions 1 and 2, offers a 12-metre-resolution binary settlement layer, distinguishing between built-up areas and non-built-up surfaces. Version 1 of the Global Urban Footprint was released in 2014 and the version 2 was released in 2016 (German Aerospace Center(DLR), 2018). These diverse settlement products offer unique insights into global settlement patterns and serve as valuable data sources for population modelling. For more detailed information on these settlement products, visit [geoservice maps](https://geoservice.dlr.de/web/maps). Importantly, these datasets are open access, allowing free data downloads for any country worldwide.

**5.Global Human Settlement Layers:** The Global Human Settlement Layers are produced by the European Commission Joint Research Centre (JRC) in collaboration with other agencies, such as the European Space Agency (ESA). This dataset offers a comprehensive open-source settlement product encompassing a wide range of settlement layers, such as built-up surface area, building height, and built-up volumes, among others. The Global Human Settlement Layers are raster files and come in different resolutions depending on the settlement product type. These datasets have global coverage and provide settlement information across numerous countries and regions. Further information on these settlement products and how to download them can be found here: [GHSL Layers](https://ghsl.jrc.ec.europa.eu/dataToolsOverview.php). Florczyk et al. (2019) also provides a comprehensive description of these settlement products. These datasets are open source and can be downloaded for any country globally.

## Use of Settlement Data in Population Modelling

Settlement data are used in modelling grided population in a variety of ways:

1. Settlement data such as building count or settled area are key input data in bottom-up gridded population estimation (see chapter 2). For example, in bottom-up population modelling approach where building count or settled area is used as input data, the predicted gridded population count is obtained as a product of the predicted density and the building count or settled area (see chapter 2 for more details on bottom-up population modelling).

2.	Settlement data are also used as a constraint layer in both top-down (see chapter 3) and bottom-up population modelling. In producing high-resolution population counts, settlement data are also used to constrain the predictions to only locations where we have settlement information to avoid making predictions at unsettled locations. Thus, settlement data serve as a proxy to extrapolate population totals for a given location.

3.	Settlement data are used as covariates to account for variabilities in population density for both bottom-up and top-down population modelling.  Building footprint metrics such as building count, building perimeter, building area, height etc are included as geospatial covariates in gridded population input for the modelling. 

4.	Settlement data can also be classified in a hierarchical pattern defining settlement typologies such as rural, urban, cities, towns, and villages, which gives a broad zone of human population density and settlement morphology in a given location [@Florczyk; @Jochem].These settlement classifications may be incorporated into bottom-up gridded population estimation methods as fixed or random effects to account for variabilities in population density attributed to the respective settlement classifications.

## Geospatial Covariates

Geospatial covariates are high-resolution raster layers used in geospatial or spatial statistical analysis to explain, model, or predict a particular phenomenon or spatial pattern. At the core of geospatial covariates is a location attribute that distinguishes it from any other dataset. Geospatial covariates have a location attribute defining the exact position or location of the dataset on the surface of the earth. Examples of geospatial covariates are the land use and land cover dataset, settlement layers, environmental and climatic variables, natural features, and socioeconomic variables. These geospatial covariates can be obtained from different sources, such as satellite imagery, aerial photography, census or survey data, weather data, etc.

Geospatial covariates play important role in gridded population estimation, allowing us to model variations in population distribution/population density attributable to the local contexts of human settlement patterns on the landscape. There are a wide variety of geospatial covariates that can be included in a gridded population estimation, ranging from land uses and land cover data products to conflict data, climate variables, physical features, infrastructure, settlement products, etc. All these geospatial covariates help inform the distribution of population patterns. 
The use of these geospatial covariates in a gridded population estimation must be informed by whether they have a significant correlation with variation in population distribution, their availability across the entire study location, and whether they can be mapped accurately as a high-resolution geospatial layer. Some covariates that may not be in the form of a gridded raster layer will require pre-processing using various interpolation or kriging methods, such as inverse distance weighting, to process them into a high-resolution geospatial layer for use in the modelling. WorldPop Open Population Repository [WOPR](https://hub.worldpop.org/project/categories?id=14) has a wide variety of geospatial covariates processed to a 100m resolution that can readily be downloaded for population and other geospatial modelling work. 

Covariates selected for population modelling may have different units of measurement. This will require a statistical method to standardise or transform the covariates in order for them to be on the same scale. Also, a large number of geospatial covariates may be assembled, requiring the use of appropriate statistical methods such as a stepwise selection process or pairwise correlation analysis to select the appropriate geospatial covariates that have a significant association with the population distribution in the modelling. A large number of geospatial covariates imposes a computational cost in building the model and making predictions at unsampled locations.

## Contribution{-}

This chapter was written by Ortis Yankey with supervision from Chris Nnanatu.
Funding for the work was provided by Grid3.
